#ifndef TENSORFLOW_XLOGX_SETTINGS_H
#define TENSORFLOW_XLOGX_SETTINGS_H

#define THROW_ERROR_FOR_NEGATIVE_LOGS_ON_CPU 0
#define FIX_DERIVATIVE_FROM_0_TO_EPSILON 0
#define EPSILON 1e-3

#endif //TENSORFLOW_XLOGX_SETTINGS_H
